QBShared = QBShared or {}
QBShared.Horses = {
	['Donkey'] = {
		['name'] = 'Donkey',
		['model'] = `A_C_Donkey_01`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',		
	},
	['Greyovero'] = {
		['name'] = 'Greyovero',
		['model'] = `A_C_Horse_AmericanPaint_Greyovero`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Overo'] = {
		['name'] = 'Overo',
		['model'] = `A_C_Horse_AmericanPaint_Overo`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['SplashedWhite'] = {
		['name'] = 'SplashedWhite',
		['model'] = `A_C_Horse_AmericanPaint_SplashedWhite`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Tobiano'] = {
		['name'] = 'Tobiano',
		['model'] = `A_C_Horse_AmericanPaint_Tobiano`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['StandardbredBlack'] = {
		['name'] = 'StandardbredBlack',
		['model'] = `A_C_Horse_AmericanStandardbred_Black`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['StandardbredBuckskin'] = {
		['name'] = 'StandardbredBuckskin',
		['model'] = `A_C_Horse_AmericanStandardbred_Buckskin`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['StandardbredPalominoDapple'] = {
		['name'] = 'StandardbredPalominoDapple',
		['model'] = `A_C_Horse_AmericanStandardbred_PalominoDapple`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['StandardbredSilverTailBuckskin'] = {
		['name'] = 'StandardbredSilverTailBuckskin',
		['model'] = `A_C_Horse_AmericanStandardbred_SilverTailBuckskin`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['AndalusianDarkBay'] = {
		['name'] = 'AndalusianDarkBay',
		['model'] = `A_C_Horse_Andalusian_DarkBay`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Perlino'] = {
		['name'] = 'Perlino',
		['model'] = `A_C_Horse_Andalusian_Perlino`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['RoseGray'] = {
		['name'] = 'RoseGray',
		['model'] = `A_C_Horse_Andalusian_RoseGray`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['BlackSnowflake'] = {
		['name'] = 'BlackSnowflake',
		['model'] = `A_C_Horse_Appaloosa_BlackSnowflake`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Blanket'] = {
		['name'] = 'Blanket',
		['model'] = `A_C_Horse_Appaloosa_Blanket`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['BrownLeopard'] = {
		['name'] = 'BrownLeopard',
		['model'] = `A_C_Horse_Appaloosa_BrownLeopard`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['FewSpottedPC'] = {
		['name'] = 'FewSpottedPC',
		['model'] = `A_C_Horse_Appaloosa_FewSpotted_PC`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Leopard'] = {
		['name'] = 'Leopard',
		['model'] = `A_C_Horse_Appaloosa_Leopard`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['LeopardBlanket'] = {
		['name'] = 'LeopardBlanket',
		['model'] = `A_C_Horse_Appaloosa_LeopardBlanket`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['ArabianBlack'] = {
		['name'] = 'ArabianBlack',
		['model'] = `A_C_Horse_Arabian_Black`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},	
	['ArabianGrey'] = {
		['name'] = 'ArabianGrey',
		['model'] = `A_C_Horse_Arabian_Grey`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['ArabianRedChestnut'] = {
		['name'] = 'ArabianRedChestnut',
		['model'] = `A_C_Horse_Arabian_RedChestnut`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['RedChestnutPC'] = {
		['name'] = 'RedChestnutPC',
		['model'] = `A_C_Horse_Arabian_RedChestnut_PC`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['RoseGreyBay'] = {
		['name'] = 'RoseGreyBay',
		['model'] = `A_C_Horse_Arabian_RoseGreyBay`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['WarpedBrindlePC'] = {
		['name'] = 'WarpedBrindlePC',
		['model'] = `A_C_Horse_Arabian_WarpedBrindle_PC`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['ArabianWhite'] = {
		['name'] = 'ArabianWhite',
		['model'] = `A_C_Horse_Arabian_White`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['ArdennesBayRoan'] = {
		['name'] = 'ArdennesBayRoan',
		['model'] = `A_C_Horse_Ardennes_BayRoan`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['IronGreyRoan'] = {
		['name'] = 'IronGreyRoan',
		['model'] = `A_C_Horse_Ardennes_IronGreyRoan`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['StrawberryRoan'] = {
		['name'] = 'StrawberryRoan',
		['model'] = `A_C_Horse_Ardennes_StrawberryRoan`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['BlondChestnut'] = {
		['name'] = 'BlondChestnut',
		['model'] = `A_C_Horse_Belgian_BlondChestnut`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['MealyChestnut'] = {
		['name'] = 'MealyChestnut',
		['model'] = `A_C_Horse_Belgian_MealyChestnut`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['WarVets'] = {
		['name'] = 'WarVets',
		['model'] = `A_C_Horse_Buell_WarVets`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['ChocolateRoan'] = {
		['name'] = 'ChocolateRoan',
		['model'] = `A_C_Horse_DutchWarmblood_ChocolateRoan`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['SealBrown'] = {
		['name'] = 'SealBrown',
		['model'] = `A_C_Horse_DutchWarmblood_SealBrown`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},	
	['SootyBuckskin'] = {
		['name'] = 'SootyBuckskin',
		['model'] = `A_C_Horse_DutchWarmblood_SootyBuckskin`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},	
	['EagleFlies'] = {
		['name'] = 'EagleFlies',
		['model'] = `A_C_Horse_EagleFlies`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},	
	['Bill'] = {
		['name'] = 'Bill',
		['model'] = `A_C_Horse_Gang_Bill`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},		
	['Charles'] = {
		['name'] = 'Charles',
		['model'] = `A_C_Horse_Gang_Charles`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['CharlesEndlessSummer'] = {
		['name'] = 'CharlesEndlessSummer',
		['model'] = `A_C_Horse_Gang_Charles_EndlessSummer`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},	
	['Dutch'] = {
		['name'] = 'Dutch',
		['model'] = `A_C_Horse_Gang_Dutch`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Hosea'] = {
		['name'] = 'Hosea',
		['model'] = `A_C_Horse_Gang_Hosea`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Javier'] = {
		['name'] = 'Javier',
		['model'] = `A_C_Horse_Gang_Javier`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['John'] = {
		['name'] = 'John',
		['model'] = `A_C_Horse_Gang_John`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Karen'] = {
		['name'] = 'Karen',
		['model'] = `A_C_Horse_Gang_Karen`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Kieran'] = {
		['name'] = 'Kieran',
		['model'] = `A_C_Horse_Gang_Kieran`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Lenny'] = {
		['name'] = 'Lenny',
		['model'] = `A_C_Horse_Gang_Lenny`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Micah'] = {
		['name'] = 'Micah',
		['model'] = `A_C_Horse_Gang_Micah`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Sadie'] = {
		['name'] = 'Sadie',
		['model'] = `A_C_Horse_Gang_Sadie`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['SadieEndlessSummer'] = {
		['name'] = 'SadieEndlessSummer',
		['model'] = `A_C_Horse_Gang_Sadie_EndlessSummer`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Sean'] = {
		['name'] = 'Sean',
		['model'] = `A_C_Horse_Gang_Sean`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Trelawney'] = {
		['name'] = 'Trelawney',
		['model'] = `A_C_Horse_Gang_Trelawney`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Uncle'] = {
		['name'] = 'Uncle',
		['model'] = `A_C_Horse_Gang_Uncle`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['UncleEndlessSummer'] = {
		['name'] = 'UncleEndlessSummer',
		['model'] = `A_C_Horse_Gang_Uncle_EndlessSummer`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['DarkDappleGrey'] = {
		['name'] = 'DarkDappleGrey',
		['model'] = `A_C_Horse_HungarianHalfbred_DarkDappleGrey`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['HungarianHalfbredFlaxenChestnut'] = {
		['name'] = 'HungarianHalfbredFlaxenChestnut',
		['model'] = `A_C_Horse_HungarianHalfbred_FlaxenChestnut`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['LiverChestnut'] = {
		['name'] = 'LiverChestnut',
		['model'] = `A_C_Horse_HungarianHalfbred_LiverChestnut`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['PiebaldTobiano'] = {
		['name'] = 'PiebaldTobiano',
		['model'] = `A_C_Horse_HungarianHalfbred_PiebaldTobiano`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['JohnEndlessSummer'] = {
		['name'] = 'JohnEndlessSummer',
		['model'] = `A_C_Horse_John_EndlessSummer`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['KentuckySaddleBlack'] = {
		['name'] = 'KentuckySaddleBlack',
		['model'] = `A_C_Horse_KentuckySaddle_Black`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['ButterMilkBuckskinPC'] = {
		['name'] = 'ButterMilkBuckskinPC',
		['model'] = `A_C_Horse_KentuckySaddle_ButterMilkBuckskin_PC`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['ChestnutPinto'] = {
		['name'] = 'ChestnutPinto',
		['model'] = `A_C_Horse_KentuckySaddle_ChestnutPinto`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['SaddleGrey'] = {
		['name'] = 'SaddleGrey',
		['model'] = `A_C_Horse_KentuckySaddle_Grey`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['SilverBay'] = {
		['name'] = 'SilverBay',
		['model'] = `A_C_Horse_KentuckySaddle_SilverBay`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['AmberChampagne'] = {
		['name'] = 'AmberChampagne',
		['model'] = `A_C_Horse_MissouriFoxTrotter_AmberChampagne`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['SableChampagne'] = {
		['name'] = 'SableChampagne',
		['model'] = `A_C_Horse_MissouriFoxTrotter_SableChampagne`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['SilverDapplePinto'] = {
		['name'] = 'SilverDapplePinto',
		['model'] = `A_C_Horse_MissouriFoxTrotter_SilverDapplePinto`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Bay'] = {
		['name'] = 'Bay',
		['model'] = `A_C_Horse_Morgan_Bay`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['MorganBayRoan'] = {
		['name'] = 'MorganBayRoan',
		['model'] = `A_C_Horse_Morgan_BayRoan`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['MorganFlaxenChestnut'] = {
		['name'] = 'MorganFlaxenChestnut',
		['model'] = `A_C_Horse_Morgan_FlaxenChestnut`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['LiverChestnutPC'] = {
		['name'] = 'LiverChestnutPC',
		['model'] = `A_C_Horse_Morgan_LiverChestnut_PC`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},	
	['Palomino'] = {
		['name'] = 'Palomino',
		['model'] = `A_C_Horse_Morgan_Palomino`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Mangy'] = {
		['name'] = 'Mangy',
		['model'] = `A_C_Horse_MP_Mangy_Backup`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Mange'] = {
		['name'] = 'Mange',
		['model'] = `A_C_Horse_MurfreeBrood_Mange_01`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},	
	['Mange2'] = {
		['name'] = 'Mange2',
		['model'] = `A_C_Horse_MurfreeBrood_Mange_02`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Mange3'] = {
		['name'] = 'Mange3',
		['model'] = `A_C_Horse_MurfreeBrood_Mange_03`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['GoldenDun'] = {
		['name'] = 'GoldenDun',
		['model'] = `A_C_Horse_Mustang_GoldenDun`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['GrulloDun'] = {
		['name'] = 'GrulloDun',
		['model'] = `A_C_Horse_Mustang_GrulloDun`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['TigerStripedBay'] = {
		['name'] = 'TigerStripedBay',
		['model'] = `A_C_Horse_Mustang_TigerStripedBay`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['WildBay'] = {
		['name'] = 'WildBay',
		['model'] = `A_C_Horse_Mustang_WildBay`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['BlueRoan'] = {
		['name'] = 'BlueRoan',
		['model'] = `A_C_Horse_Nokota_BlueRoan`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['ReverseDappleRoan'] = {
		['name'] = 'ReverseDappleRoan',
		['model'] = `A_C_Horse_Nokota_ReverseDappleRoan`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['WhiteRoan'] = {
		['name'] = 'WhiteRoan',
		['model'] = `A_C_Horse_Nokota_WhiteRoan`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['ShireDarkBay'] = {
		['name'] = 'ShireDarkBay',
		['model'] = `A_C_Horse_Shire_DarkBay`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['LightGrey'] = {
		['name'] = 'LightGrey',
		['model'] = `A_C_Horse_Shire_LightGrey`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['RavenBlack'] = {
		['name'] = 'RavenBlack',
		['model'] = `A_C_Horse_Shire_RavenBlack`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['SuffolkPunchRedChestnut'] = {
		['name'] = 'SuffolkPunchRedChestnut',
		['model'] = `A_C_Horse_SuffolkPunch_RedChestnut`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['PunchSorrel'] = {
		['name'] = 'PunchSorrel',
		['model'] = `A_C_Horse_SuffolkPunch_Sorrel`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['BlackRabicano'] = {
		['name'] = 'BlackRabicano',
		['model'] = `A_C_Horse_TennesseeWalker_BlackRabicano`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Chestnut'] = {
		['name'] = 'Chestnut',
		['model'] = `A_C_Horse_TennesseeWalker_Chestnut`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['DappleBay'] = {
		['name'] = 'DappleBay',
		['model'] = `A_C_Horse_TennesseeWalker_DappleBay`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['FlaxenRoan'] = {
		['name'] = 'FlaxenRoan',
		['model'] = `A_C_Horse_TennesseeWalker_FlaxenRoan`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['GoldPalominoPC'] = {
		['name'] = 'GoldPalominoPC',
		['model'] = `A_C_Horse_TennesseeWalker_GoldPalomino_PC`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['MahoganyBay'] = {
		['name'] = 'MahoganyBay',
		['model'] = `A_C_Horse_TennesseeWalker_MahoganyBay`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['RedRoan'] = {
		['name'] = 'RedRoan',
		['model'] = `A_C_Horse_TennesseeWalker_RedRoan`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['BlackChestnut'] = {
		['name'] = 'BlackChestnut',
		['model'] = `A_C_Horse_Thoroughbred_BlackChestnut`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['BloodBay'] = {
		['name'] = 'BloodBay',
		['model'] = `A_C_Horse_Thoroughbred_BloodBay`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Brindle'] = {
		['name'] = 'Brindle',
		['model'] = `A_C_Horse_Thoroughbred_Brindle`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['DappleGrey'] = {
		['name'] = 'DappleGrey',
		['model'] = `A_C_Horse_Thoroughbred_DappleGrey`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['ReverseDappleBlack'] = {
		['name'] = 'ReverseDappleBlack',
		['model'] = `A_C_Horse_Thoroughbred_ReverseDappleBlack`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['TurkomanDarkBay'] = {
		['name'] = 'TurkomanDarkBay',
		['model'] = `A_C_Horse_Turkoman_DarkBay`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Gold'] = {
		['name'] = 'Gold',
		['model'] = `A_C_Horse_Turkoman_Gold`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Silver'] = {
		['name'] = 'Silver',
		['model'] = `A_C_Horse_Turkoman_Silver`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Winter2'] = {
		['name'] = 'Winter2',
		['model'] = `A_C_Horse_Winter02_01`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Mule'] = {
		['name'] = 'Mule',
		['model'] = `A_C_HorseMule_01`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['MulePainted'] = {
		['name'] = 'MulePainted',
		['model'] = `A_C_HorseMulePainted_01`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
	['Horse'] = {
		['name'] = 'Horse',
		['model'] = `P_C_Horse_01`,
		['price'] = 10,
		['category'] = 'horse',
		['shop'] = '',
	},
}
