QBShared = QBShared or {}
QBShared.Vehicles = {
	['CART01'] = {
		['name'] = 'Wooden Cart 1',
		['brand'] = '?',
		['model'] = 'CART01',
		['price'] = 10,
		['category'] = 'carts',
		['hash'] = '-824257932',
		['shop'] = 'cart',
	},
	['CART02'] = {
		['name'] = 'Wooden Cart 2',
		['brand'] = '?',
		['model'] = 'CART02',
		['price'] = 10,
		['category'] = 'carts',
		['hash'] = '-2053881888',
		['shop'] = 'cart',
	},
	['CART03'] = {
		['name'] = 'Wooden Cart 3',
		['brand'] = '?',
		['model'] = 'CART03',
		['price'] = 10,
		['category'] = 'carts',
		['hash'] = '-1347283941',
		['shop'] = 'cart',
	},
	['CART04'] = {
		['name'] = 'Wooden Cart 4',
		['brand'] = '?',
		['model'] = 'CART04',
		['price'] = 10,
		['category'] = 'carts',
		['hash'] = '-570691410',
		['shop'] = 'cart',
	},
	['CART05'] = {
		['name'] = 'Wooden Cart 5',
		['brand'] = '?',
		['model'] = 'CART05',
		['price'] = 10,
		['category'] = 'carts',
		['hash'] = '374792535',
		['shop'] = 'cart',
	},
	['CART06'] = {
		['name'] = 'Wooden Cart 6',
		['brand'] = '?',
		['model'] = 'CART06',
		['price'] = 10,
		['category'] = 'carts',
		['hash'] = '219205323',
		['shop'] = 'cart',
	},
	['CART07'] = {
		['name'] = 'Wooden Cart 7',
		['brand'] = '?',
		['model'] = 'CART07',
		['price'] = 10,
		['category'] = 'carts',
		['hash'] = '47200842',
		['shop'] = 'cart',
	},
	['CART08'] = {
		['name'] = 'Wooden Cart 8',
		['brand'] = '?',
		['model'] = 'CART08',
		['price'] = 10,
		['category'] = 'carts',
		['hash'] = '-377157708',
		['shop'] = 'cart',
	},
	['BUGGY01'] = {
		['name'] = 'Luxurious Buggy 1',
		['brand'] = '?',
		['model'] = 'BUGGY01',
		['price'] = 10,
		['category'] = 'Buggies',
		['hash'] = '-1278978750',
		['shop'] = 'cart',
	},
	['BUGGY02'] = {
		['name'] = 'Luxurious Buggy 2',
		['brand'] = '?',
		['model'] = 'BUGGY02',
		['price'] = 10,
		['category'] = 'Buggies',
		['hash'] = '-1100387700',
		['shop'] = 'cart',
	},
	['BUGGY03'] = {
		['name'] = 'Luxurious Buggy 3',
		['brand'] = '?',
		['model'] = 'BUGGY03',
		['price'] = 10,
		['category'] = 'Buggies',
		['hash'] = '-1861840953',
		['shop'] = 'cart',
	},
	['COACH2'] = {
		['name'] = 'Special Transport 1',
		['brand'] = '?',
		['model'] = 'COACH2',
		['price'] = 10,
		['category'] = 'Specials',
		['hash'] = '1761016051',
		['shop'] = 'cart',
	},
	['COACH3'] = {
		['name'] = 'Special Transport 2',
		['brand'] = '?',
		['model'] = 'COACH3',
		['price'] = 10,
		['category'] = 'Specials',
		['hash'] = '-136833353',
		['shop'] = 'cart',
	},
	['COACH4'] = {
		['name'] = 'Special Transport 3',
		['brand'] = '?',
		['model'] = 'COACH4',
		['price'] = 10,
		['category'] = 'Specials',
		['hash'] = '93893176',
		['shop'] = 'cart',
	},
	['COACH5'] = {
		['name'] = 'Special Transport 4',
		['brand'] = '?',
		['model'] = 'COACH5',
		['price'] = 10,
		['category'] = 'Specials',
		['hash'] = '-1826304690',
		['shop'] = 'cart',
	},
	['COACH6'] = {
		['name'] = 'Special Transport 5',
		['brand'] = '?',
		['model'] = 'COACH6',
		['price'] = 10,
		['category'] = 'Specials',
		['hash'] = '-1544786211',
		['shop'] = 'cart',
	}
}
