QBShared = QBShared or {}
QBShared.Vehicles = {
	['armoredCar01x'] = {
		['name'] = 'Armored Car 1',
		['model'] = 'armoredCar01x',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '-923856480',
		['shop'] = 'cart',
	},
	['armoredCar03x'] = {
		['name'] = 'Armored Car 3',
		['model'] = 'armoredCar03x',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '583628516',
		['shop'] = 'cart',
	},
	['ArmySupplyWagon'] = {
		['name'] = 'Army Supply Wagon',
		['model'] = 'ArmySupplyWagon',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '661519966',
		['shop'] = 'cart',
	},
	['boatsteam02x'] = {
		['name'] = 'Steam Boat',
		['model'] = 'boatsteam02x',
		['price'] = 10,
		['category'] = 'boat',
		['hash'] = '-2022805833',
		['shop'] = 'boat',
	},
	['bountywagon01x'] = {
		['name'] = 'Bounty Wagon',
		['model'] = 'bountywagon01x',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '-2044900246',
		['shop'] = 'cart',
	},
	['buggy01'] = {
		['name'] = 'Luxurious Buggy 1',
		['model'] = 'buggy01',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '-1278978750',
		['shop'] = 'cart',
	},
	['buggy02'] = {
		['name'] = 'Luxurious Buggy 2',
		['model'] = 'buggy02',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '-1100387700',
		['shop'] = 'cart',
	},
	['buggy03'] = {
		['name'] = 'Luxurious Buggy 3',
		['model'] = 'buggy03',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '-1861840953',
		['shop'] = 'cart',
	},
	['canoe'] = {
		['name'] = 'Canoe',
		['model'] = 'canoe',
		['price'] = 10,
		['category'] = 'boat',
		['hash'] = '1468884243',
		['shop'] = 'boat',
	},
	['canoeTreeTrunk'] = {
		['name'] = 'Tree Trunk Canoe',
		['model'] = 'canoeTreeTrunk',
		['price'] = 10,
		['category'] = 'boat',
		['hash'] = '-666024656',
		['shop'] = 'boat',
	},
	['cart01'] = {
		['name'] = 'Wooden Cart 1',
		['model'] = 'cart01',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '-824257932',
		['shop'] = 'cart',
	},
	['cart02'] = {
		['name'] = 'Wooden Cart 2',
		['model'] = 'cart02',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '-2053881888',
		['shop'] = 'cart',
	},
	['cart03'] = {
		['name'] = 'Wooden Cart 3',
		['model'] = 'cart03',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '-1347283941',
		['shop'] = 'cart',
	},
	['cart04'] = {
		['name'] = 'Wooden Cart 4',
		['model'] = 'cart04',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '-570691410',
		['shop'] = 'cart',
	},
	['cart05'] = {
		['name'] = 'Wooden Cart 5',
		['model'] = 'cart05',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '374792535',
		['shop'] = 'cart',
	},
	['cart06'] = {
		['name'] = 'Wooden Cart 6',
		['model'] = 'cart06',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '219205323',
		['shop'] = 'cart',
	},
	['cart07'] = {
		['name'] = 'Wooden Cart 7',
		['model'] = 'cart07',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '47200842',
		['shop'] = 'cart',
	},
	['cart08'] = {
		['name'] = 'Wooden Cart 8',
		['model'] = 'cart08',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '-377157708',
		['shop'] = 'cart',
	},
	['chuckwagon000x'] = {
		['name'] = 'Chuck Wagon',
		['model'] = 'chuckwagon000x',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '1596452133',
		['shop'] = 'cart',
	},
	['chuckwagon002x'] = {
		['name'] = 'Chuck Wagon 2',
		['model'] = 'chuckwagon002x',
		['price'] = 10,
		['category'] = 'cart',
		['hash'] = '1770617692',
		['shop'] = 'cart',
	},
	['coach2'] = {
		['name'] = 'Coach 2',
		['model'] = 'coach2',
		['price'] = 10,
		['category'] = 'coach',
		['hash'] = '1761016051',
		['shop'] = 'cart',
	},
	['coach3'] = {
		['name'] = 'Coach 3',
		['model'] = 'coach3',
		['price'] = 10,
		['category'] = 'coach',
		['hash'] = '-136833353',
		['shop'] = 'cart',
	},
	['coach4'] = {
		['name'] = 'Coach 4',
		['model'] = 'coach4',
		['price'] = 10,
		['category'] = 'coach',
		['hash'] = '93893176',
		['shop'] = 'cart',
	},
	['coach5'] = {
		['name'] = 'Coach 5',
		['brand'] = '?',
		['model'] = 'coach5',
		['price'] = 10,
		['category'] = 'coach',
		['hash'] = '-1826304690',
		['shop'] = 'cart',
	},
	['coach6'] = {
		['name'] = 'Coach 6',
		['brand'] = '?',
		['model'] = 'coach6',
		['price'] = 10,
		['category'] = 'coach',
		['hash'] = '-1544786211',
		['shop'] = 'cart',
	},
	['coal_wagon'] = {
		['name'] = 'Coal Wagon',
		['brand'] = '?',
		['model'] = 'coal_wagon',
		['price'] = 10,
		['category'] = 'utility',
		['hash'] = '1642867136',
		['shop'] = 'cart',
	}
}
