QBShared = QBShared or {}
QBShared.Weapons = {
	[`WEAPON_BOW`]									= {['name'] = 'weapon_bow', 							['attachPoint'] = 7,	['label'] = 'Flatbow',							['ammotype'] = 'AMMO_ARROW',	 		['image'] = 'weapon_bow01.png',					},
	[`WEAPON_BOW_IMPROVED`]							= {['name'] = 'weapon_bow_improved', 					['attachPoint'] = 7,	['label'] = 'Sturdy Flatbow',					['ammotype'] = 'AMMO_ARROW',	 		['image'] = 'weapon_bow02.png',					},
	[`WEAPON_LASSO`]								= {['name'] = 'weapon_lasso', 							['attachPoint'] = 5,	['label'] = 'Lasso',							['ammotype'] = nil,				 		['image'] = 'weapon_lasso01.png',				},
	[`WEAPON_LASSO_REINFORCED`]						= {['name'] = 'weapon_lasso_reinforced', 				['attachPoint'] = 5,	['label'] = 'Sturdy Lasso',						['ammotype'] = nil,				 		['image'] = 'weapon_lasso02.png',				},
	[`WEAPON_REVOLVER_CATTLEMAN`] 					= {['name'] = 'weapon_revolver_cattleman',				['attachPoint'] = 2, 	['label'] = 'Colt M1873 Single Action',			['ammotype'] = 'AMMO_REVOLVER', 		['image'] = 'weapon_revolver01.png',			},
	[`WEAPON_REVOLVER_CATTLEMAN_MEXICAN`] 			= {['name'] = 'weapon_revolver_cattleman_mexican',		['attachPoint'] = 2, 	['label'] = 'Steel Colt M1873',					['ammotype'] = 'AMMO_REVOLVER', 		['image'] = 'weapon_revolver02.png',			},
	[`WEAPON_REVOLVER_DOUBLEACTION_GAMBLER`] 		= {['name'] = 'weapon_revolver_doubleaction_gambler', 	['attachPoint'] = 2,	['label'] = 'Colt M1892 Double-action',			['ammotype'] = 'AMMO_REVOLVER', 		['image'] = 'weapon_revolver03.png',			},
	[`WEAPON_REVOLVER_SCHOFIELD`] 					= {['name'] = 'weapon_revolver_schofield',				['attachPoint'] = 2, 	['label'] = 'Smith & Wesson No. 3',				['ammotype'] = 'AMMO_REVOLVER', 		['image'] = 'weapon_revolver04.png',			},
	[`WEAPON_REVOLVER_LEMAT`] 						= {['name'] = 'weapon_revolver_lemat',					['attachPoint'] = 2, 	['label'] = 'LeMat Revolver',					['ammotype'] = 'AMMO_REVOLVER', 		['image'] = 'weapon_revolver05.png',			},
	[`WEAPON_REVOLVER_NAVY`] 						= {['name'] = 'weapon_revolver_navy', 					['attachPoint'] = 2,	['label'] = 'Navy Revolver 1851',				['ammotype'] = 'AMMO_REVOLVER', 		['image'] = 'weapon_revolver_navy.png',			},
	[`WEAPON_PISTOL_VOLCANIC`] 						= {['name'] = 'weapon_pistol_volcanic',					['attachPoint'] = 2, 	['label'] = 'Volcanic Pistol',					['ammotype'] = 'AMMO_PISTOL',	 		['image'] = 'weapon_pistol01.png',				},
	[`WEAPON_PISTOL_M1899`] 						= {['name'] = 'weapon_pistol_m1899', 					['attachPoint'] = 2,	['label'] = 'FN Browning M1900',				['ammotype'] = 'AMMO_PISTOL',	 		['image'] = 'weapon_pistol02.png',				},
	[`WEAPON_PISTOL_MAUSER`] 						= {['name'] = 'weapon_pistol_mauser', 					['attachPoint'] = 2,	['label'] = 'Mauser C96',						['ammotype'] = 'AMMO_PISTOL',	 		['image'] = 'weapon_pistol03.png',				},
	[`WEAPON_PISTOL_SEMIAUTO`] 						= {['name'] = 'weapon_pistol_semiauto',					['attachPoint'] = 2, 	['label'] = 'Borchardt C-93',					['ammotype'] = 'AMMO_PISTOL',	 		['image'] = 'weapon_pistol04.png',				},
	[`WEAPON_REPEATER_CARBINE`] 					= {['name'] = 'weapon_repeater_carbine', 				['attachPoint'] = 9,	['label'] = 'Spencer Model 1865',				['ammotype'] = 'AMMO_REPEATER',	 		['image'] = 'weapon_repeater01.png',			},
	[`WEAPON_REPEATER_WINCHESTER`] 					= {['name'] = 'weapon_repeater_winchester', 			['attachPoint'] = 9,	['label'] = 'Winchester Model 1866',			['ammotype'] = 'AMMO_REPEATER',	 		['image'] = 'weapon_repeater02.png',			},
	[`WEAPON_REPEATER_HENRY`] 						= {['name'] = 'weapon_repeater_henry', 					['attachPoint'] = 9,	['label'] = 'Henry Model 1860',					['ammotype'] = 'AMMO_REPEATER',	 		['image'] = 'weapon_repeater03.png',			},
	[`WEAPON_REPEATER_EVANS`] 						= {['name'] = 'weapon_repeater_evans', 					['attachPoint'] = 9,	['label'] = 'Evans Repeating Rifle',			['ammotype'] = 'AMMO_REPEATER',	 		['image'] = 'weapon_repeater_evans.png',		},
	[`WEAPON_RIFLE_VARMINT`] 						= {['name'] = 'weapon_rifle_varmint', 					['attachPoint'] = 9,	['label'] = 'Winchester Model 1890',			['ammotype'] = 'AMMO_RIFLE',	 		['image'] = 'weapon_rifle01.png',				},
	[`WEAPON_RIFLE_SPRINGFIELD`] 					= {['name'] = 'weapon_rifle_springfield', 				['attachPoint'] = 9,	['label'] = 'Springfield Model 1873',			['ammotype'] = 'AMMO_RIFLE',	 		['image'] = 'weapon_rifle02.png',				},
	[`WEAPON_RIFLE_BOLTACTION`] 					= {['name'] = 'weapon_rifle_boltaction', 				['attachPoint'] = 9,	['label'] = 'Springfield Model 1892',			['ammotype'] = 'AMMO_RIFLE',	 		['image'] = 'weapon_rifle03.png',				},
	[`WEAPON_RIFLE_ELEPHANT`] 						= {['name'] = 'weapon_rifle_elephant', 					['attachPoint'] = 9,	['label'] = 'Elephant Rifle',					['ammotype'] = 'AMMO_RIFLE',	 		['image'] = 'weapon_rifle04.png',				},
	[`WEAPON_SHOTGUN_DOUBLEBARREL`] 				= {['name'] = 'weapon_shotgun_doublebarrel', 			['attachPoint'] = 9,	['label'] = 'Colt Hammer Shotgun 1878',			['ammotype'] = 'AMMO_SHOTGUN',	 		['image'] = 'weapon_shotgun01.png',				},
	[`WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC`] 			= {['name'] = 'weapon_shotgun_doublebarrel_exotic', 	['attachPoint'] = 9,	['label'] = 'Steel Hammer Shotgun 1878',		['ammotype'] = 'AMMO_SHOTGUN',	 		['image'] = 'weapon_shotgun02.png',				},
	[`WEAPON_SHOTGUN_SAWEDOFF`] 					= {['name'] = 'weapon_shotgun03', 						['attachPoint'] = 9,	['label'] = 'Hamerless Shotgun 1883',			['ammotype'] = 'AMMO_SHOTGUN',	 		['image'] = 'weapon_shotgun03.png',				},
	[`WEAPON_SHOTGUN_SEMIAUTO`] 					= {['name'] = 'weapon_shotgun_semiauto', 				['attachPoint'] = 9,	['label'] = 'Browning Auto-5',					['ammotype'] = 'AMMO_SHOTGUN',	 		['image'] = 'weapon_shotgun06.png',				},
	[`WEAPON_SNIPERRIFLE_ROLLINGBLOCK`] 			= {['name'] = 'weapon_sniperrifle_rollingblock', 		['attachPoint'] = 10,	['label'] = 'Remington M1867',					['ammotype'] = 'AMMO_RIFLE',	 		['image'] = 'weapon_sniper01.png',				},
	[`WEAPON_SNIPERRIFLE_ROLLINGBLOCK_EXOTIC`]		= {['name'] = 'weapon_sniperrifle_rollingblock_exotic', ['attachPoint'] = 10,	['label'] = 'Steel Remington M1867',			['ammotype'] = 'AMMO_RIFLE',	 		['image'] = 'weapon_sniper02.png',				},
	[`WEAPON_SNIPERRIFLE_CARCANO`]					= {['name'] = 'weapon_sniperrifle_carcano', 			['attachPoint'] = 10,	['label'] = 'Carcano 1891 Short Rifle',			['ammotype'] = 'AMMO_RIFLE',	 		['image'] = 'weapon_sniper03.png',				},
	[`WEAPON_MELEE_KNIFE`]							= {['name'] = 'weapon_melee_knife', 					['attachPoint'] = 4, 	['label'] = 'Knife',							['ammotype'] = nil,				 		['image'] = 'weapon_knife01.png',				},
	[`WEAPON_MELEE_KNIFE_JAWBONE`]					= {['name'] = 'weapon_melee_knife_jawbone',				['attachPoint'] = 4, 	['label'] = 'Jawbone Knife',					['ammotype'] = nil,				 		['image'] = 'weapon_knife02.png',				},
	[`WEAPON_MELEE_HAMMER`]							= {['name'] = 'weapon_melee_hammer',					['attachPoint'] = 13, 	['label'] = 'Hammer',							['ammotype'] = nil,				 		['image'] = 'weapon_hammer.png',				},
	[`WEAPON_THROWN_DYNAMITE`]						= {['name'] = 'weapon_thrown_dynamite',					['attachPoint'] = 6,	['label'] = 'Throwable Dynamite',				['ammotype'] = 'AMMO_DYNAMITE',			['image'] = 'weapon_throw_dynamite.png',		},
	[`WEAPON_THROWN_MOLOTOV`]						= {['name'] = 'weapon_thrown_molotov',					['attachPoint'] = 6,	['label'] = 'Throwable Molotov',				['ammotype'] = 'AMMO_MOLOTOV',			['image'] = 'weapon_throw_molotov.png',			},
	[`WEAPON_THROWN_THROWING_KNIVES`]				= {['name'] = 'weapon_thrown_throwing_knives',			['attachPoint'] = 6,	['label'] = 'Throwing Knives',					['ammotype'] = 'AMMO_THROWING_KNIVES',	['image'] = 'weapon_throw_knives.png',			},
	[`WEAPON_THROWN_TOMAHAWK`]						= {['name'] = 'weapon_thrown_tomahawk',					['attachPoint'] = 6,	['label'] = 'Throwable Axe',					['ammotype'] = nil,				 		['image'] = 'weapon_throw_axe01.png',			},
	[`WEAPON_THROWN_TOMAHAWK_ANCIENT`]				= {['name'] = 'weapon_thrown_tomahawk_ancient',			['attachPoint'] = 6,	['label'] = 'Throwable Old Axe',				['ammotype'] = nil,				 		['image'] = 'weapon_throw_axe02.png',			},
	[`WEAPON_THROWN_BOLAS`]							= {['name'] = 'weapon_thrown_bolas',					['attachPoint'] = 6,	['label'] = 'Throwable Bolas',					['ammotype'] = nil,				 		['image'] = 'weapon_throw_bolas.png',			},
	[`WEAPON_MELEE_CLEAVER`]						= {['name'] = 'weapon_melee_cleaver',					['attachPoint'] = 3,	['label'] = 'Throwable Cleaver',				['ammotype'] = nil,				 		['image'] = 'weapon_throw_cleaver.png',			},
	[`WEAPON_MELEE_LANTERN`]						= {['name'] = 'weapon_melee_lantern',					['attachPoint'] = 11,	['label'] = 'Silver Lantern',					['ammotype'] = nil,				 		['image'] = 'weapon_lantern01.png',				},
	[`WEAPON_MELEE_DAVY_LANTERN`]					= {['name'] = 'weapon_melee_davy_lantern',				['attachPoint'] = 11,	['label'] = 'Golden Lantern',					['ammotype'] = nil,				 		['image'] = 'weapon_lantern02.png',				},
	[`WEAPON_MELEE_TORCH`]							= {['name'] = 'weapon_melee_torch',						['attachPoint'] = 13,	['label'] = 'Wooden Torch',						['ammotype'] = nil,				 		['image'] = 'weapon_torch.png',					},
	[`WEAPON_MELEE_HATCHET`]						= {['name'] = 'weapon_melee_hatchet',					['attachPoint'] = 13,	['label'] = 'Hatchet',							['ammotype'] = nil,				 		['image'] = 'weapon_hatchet.png',				},
	[`WEAPON_MELEE_MACHETE`]						= {['name'] = 'weapon_melee_machete',					['attachPoint'] = 13,	['label'] = 'Machete',							['ammotype'] = nil,				 		['image'] = 'weapon_machete.png',				}
}
